---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: variant
flagType: string
description: ""
labels:

availableValues:
  - var2
  - var3
  - vat1
  - var4
  - var5
  - var6
  - var7
  - var8
  - var9

isPermanent: false
